import numpy as np
import matplotlib.pyplot as plt
x = np.linspace(0,2*np.pi,100)
y = np.sin(x)
# plt.plot(x,y)
# plt.show()
a = [0,1,2]
b = [4,5,6]
c = [7,8,9]
d = [1,12,3]
# plt.plot(a,b,'r--',c,d,'b*')
# plt.show()
t = np.arange(0.0,2.0,0.1)
s = np.sin(t*np.pi)
# plt.plot(t,s,'r--', label='a')
# plt.plot( t*2,s,'--', label='b')
# plt.xlabel('this is x')
# plt.ylabel('this is y')
# plt.title('this is title')
# plt.legend()
# plt.show()
x1 = np.linspace(0.0, 5.0)
y1 = np.sin(np.pi*x1)
y2 = np.sin(np.pi*x1*2)
# plt.plot(x1,y1,'b--', label='sin(pi*x1)')
# plt.ylabel('y1 value')
# plt.plot(x1,y2,'r--', label='sin(pi*2x1)')
# plt.ylabel('y2 value')
# plt.xlabel('x1 value')
# plt.title('title is x-y value')
# plt.legend()
# plt.show()
# plt.subplot(221)
# plt.plot(x1,y1,'b--')
# plt.ylabel('y1')
# plt.subplot(222)
# plt.plot(x1,y2,'r--')
# plt.ylabel('y2')
# plt.subplot(223)
# plt.plot(x1,y2,'b*')
# plt.ylabel('y2')
# plt.subplot(224)
# plt.plot(x1,y2,'r*')
# plt.ylabel('y2')
# plt.xlabel('x')
# plt.show()
figure, ax = plt.subplots(2,2)
ax[0][0].plot(x1,y1)
ax[0][1].plot(x1,y2)
plt.show()
